// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: analytics/v1/analytics.proto

package analyticsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalyticsService_GetGeneralStats_FullMethodName            = "/analytics.v1.AnalyticsService/GetGeneralStats"
	AnalyticsService_GetAverageLengthByCategory_FullMethodName = "/analytics.v1.AnalyticsService/GetAverageLengthByCategory"
)

// AnalyticsServiceClient is the client API for AnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyticsServiceClient interface {
	// general statistics:
	// - average length overall
	// - average length last 10
	// - category shares (time-based)
	GetGeneralStats(ctx context.Context, in *GetGeneralStatsRequest, opts ...grpc.CallOption) (*GetGeneralStatsResponse, error)
	// average session length for a single category (category_id is required)
	GetAverageLengthByCategory(ctx context.Context, in *GetAverageLengthByCategoryRequest, opts ...grpc.CallOption) (*GetAverageLengthByCategoryResponse, error)
}

type analyticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsServiceClient(cc grpc.ClientConnInterface) AnalyticsServiceClient {
	return &analyticsServiceClient{cc}
}

func (c *analyticsServiceClient) GetGeneralStats(ctx context.Context, in *GetGeneralStatsRequest, opts ...grpc.CallOption) (*GetGeneralStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGeneralStatsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetGeneralStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetAverageLengthByCategory(ctx context.Context, in *GetAverageLengthByCategoryRequest, opts ...grpc.CallOption) (*GetAverageLengthByCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAverageLengthByCategoryResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetAverageLengthByCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServiceServer is the server API for AnalyticsService service.
// All implementations must embed UnimplementedAnalyticsServiceServer
// for forward compatibility.
type AnalyticsServiceServer interface {
	// general statistics:
	// - average length overall
	// - average length last 10
	// - category shares (time-based)
	GetGeneralStats(context.Context, *GetGeneralStatsRequest) (*GetGeneralStatsResponse, error)
	// average session length for a single category (category_id is required)
	GetAverageLengthByCategory(context.Context, *GetAverageLengthByCategoryRequest) (*GetAverageLengthByCategoryResponse, error)
	mustEmbedUnimplementedAnalyticsServiceServer()
}

// UnimplementedAnalyticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyticsServiceServer struct{}

func (UnimplementedAnalyticsServiceServer) GetGeneralStats(context.Context, *GetGeneralStatsRequest) (*GetGeneralStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGeneralStats not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetAverageLengthByCategory(context.Context, *GetAverageLengthByCategoryRequest) (*GetAverageLengthByCategoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAverageLengthByCategory not implemented")
}
func (UnimplementedAnalyticsServiceServer) mustEmbedUnimplementedAnalyticsServiceServer() {}
func (UnimplementedAnalyticsServiceServer) testEmbeddedByValue()                          {}

// UnsafeAnalyticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServiceServer will
// result in compilation errors.
type UnsafeAnalyticsServiceServer interface {
	mustEmbedUnimplementedAnalyticsServiceServer()
}

func RegisterAnalyticsServiceServer(s grpc.ServiceRegistrar, srv AnalyticsServiceServer) {
	// If the following call panics, it indicates UnimplementedAnalyticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyticsService_ServiceDesc, srv)
}

func _AnalyticsService_GetGeneralStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGeneralStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetGeneralStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetGeneralStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetGeneralStats(ctx, req.(*GetGeneralStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetAverageLengthByCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAverageLengthByCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetAverageLengthByCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetAverageLengthByCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetAverageLengthByCategory(ctx, req.(*GetAverageLengthByCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticsService_ServiceDesc is the grpc.ServiceDesc for AnalyticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analytics.v1.AnalyticsService",
	HandlerType: (*AnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGeneralStats",
			Handler:    _AnalyticsService_GetGeneralStats_Handler,
		},
		{
			MethodName: "GetAverageLengthByCategory",
			Handler:    _AnalyticsService_GetAverageLengthByCategory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "analytics/v1/analytics.proto",
}
