// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: analytics/v1/analytics.proto

package analyticsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetGeneralStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGeneralStatsRequest) Reset() {
	*x = GetGeneralStatsRequest{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGeneralStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGeneralStatsRequest) ProtoMessage() {}

func (x *GetGeneralStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGeneralStatsRequest.ProtoReflect.Descriptor instead.
func (*GetGeneralStatsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *GetGeneralStatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CategoryShare struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// category_id can be "uncategorized"
	CategoryId string `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	// 0..1 share, time-based: total_seconds(category) / total_seconds(overall)
	Share         float64 `protobuf:"fixed64,2,opt,name=share,proto3" json:"share,omitempty"`
	TotalSeconds  int64   `protobuf:"varint,3,opt,name=total_seconds,json=totalSeconds,proto3" json:"total_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryShare) Reset() {
	*x = CategoryShare{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryShare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryShare) ProtoMessage() {}

func (x *CategoryShare) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryShare.ProtoReflect.Descriptor instead.
func (*CategoryShare) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *CategoryShare) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *CategoryShare) GetShare() float64 {
	if x != nil {
		return x.Share
	}
	return 0
}

func (x *CategoryShare) GetTotalSeconds() int64 {
	if x != nil {
		return x.TotalSeconds
	}
	return 0
}

type GetGeneralStatsResponse struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	AverageLengthOverallSeconds float64                `protobuf:"fixed64,1,opt,name=average_length_overall_seconds,json=averageLengthOverallSeconds,proto3" json:"average_length_overall_seconds,omitempty"`
	AverageLengthLast10Seconds  float64                `protobuf:"fixed64,2,opt,name=average_length_last10_seconds,json=averageLengthLast10Seconds,proto3" json:"average_length_last10_seconds,omitempty"`
	CategoryShares              []*CategoryShare       `protobuf:"bytes,3,rep,name=category_shares,json=categoryShares,proto3" json:"category_shares,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *GetGeneralStatsResponse) Reset() {
	*x = GetGeneralStatsResponse{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGeneralStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGeneralStatsResponse) ProtoMessage() {}

func (x *GetGeneralStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGeneralStatsResponse.ProtoReflect.Descriptor instead.
func (*GetGeneralStatsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *GetGeneralStatsResponse) GetAverageLengthOverallSeconds() float64 {
	if x != nil {
		return x.AverageLengthOverallSeconds
	}
	return 0
}

func (x *GetGeneralStatsResponse) GetAverageLengthLast10Seconds() float64 {
	if x != nil {
		return x.AverageLengthLast10Seconds
	}
	return 0
}

func (x *GetGeneralStatsResponse) GetCategoryShares() []*CategoryShare {
	if x != nil {
		return x.CategoryShares
	}
	return nil
}

type GetAverageLengthByCategoryRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// required; can be "uncategorized"
	CategoryId    string `protobuf:"bytes,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAverageLengthByCategoryRequest) Reset() {
	*x = GetAverageLengthByCategoryRequest{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAverageLengthByCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAverageLengthByCategoryRequest) ProtoMessage() {}

func (x *GetAverageLengthByCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAverageLengthByCategoryRequest.ProtoReflect.Descriptor instead.
func (*GetAverageLengthByCategoryRequest) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *GetAverageLengthByCategoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetAverageLengthByCategoryRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

type GetAverageLengthByCategoryResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CategoryId           string                 `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	AverageLengthSeconds float64                `protobuf:"fixed64,2,opt,name=average_length_seconds,json=averageLengthSeconds,proto3" json:"average_length_seconds,omitempty"`
	Count                int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	SumSeconds           int64                  `protobuf:"varint,4,opt,name=sum_seconds,json=sumSeconds,proto3" json:"sum_seconds,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetAverageLengthByCategoryResponse) Reset() {
	*x = GetAverageLengthByCategoryResponse{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAverageLengthByCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAverageLengthByCategoryResponse) ProtoMessage() {}

func (x *GetAverageLengthByCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAverageLengthByCategoryResponse.ProtoReflect.Descriptor instead.
func (*GetAverageLengthByCategoryResponse) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *GetAverageLengthByCategoryResponse) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *GetAverageLengthByCategoryResponse) GetAverageLengthSeconds() float64 {
	if x != nil {
		return x.AverageLengthSeconds
	}
	return 0
}

func (x *GetAverageLengthByCategoryResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetAverageLengthByCategoryResponse) GetSumSeconds() int64 {
	if x != nil {
		return x.SumSeconds
	}
	return 0
}

var File_analytics_v1_analytics_proto protoreflect.FileDescriptor

const file_analytics_v1_analytics_proto_rawDesc = "" +
	"\n" +
	"\x1canalytics/v1/analytics.proto\x12\fanalytics.v1\"1\n" +
	"\x16GetGeneralStatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"k\n" +
	"\rCategoryShare\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\tR\n" +
	"categoryId\x12\x14\n" +
	"\x05share\x18\x02 \x01(\x01R\x05share\x12#\n" +
	"\rtotal_seconds\x18\x03 \x01(\x03R\ftotalSeconds\"\xe7\x01\n" +
	"\x17GetGeneralStatsResponse\x12C\n" +
	"\x1eaverage_length_overall_seconds\x18\x01 \x01(\x01R\x1baverageLengthOverallSeconds\x12A\n" +
	"\x1daverage_length_last10_seconds\x18\x02 \x01(\x01R\x1aaverageLengthLast10Seconds\x12D\n" +
	"\x0fcategory_shares\x18\x03 \x03(\v2\x1b.analytics.v1.CategoryShareR\x0ecategoryShares\"]\n" +
	"!GetAverageLengthByCategoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\tR\n" +
	"categoryId\"\xb2\x01\n" +
	"\"GetAverageLengthByCategoryResponse\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\tR\n" +
	"categoryId\x124\n" +
	"\x16average_length_seconds\x18\x02 \x01(\x01R\x14averageLengthSeconds\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\x12\x1f\n" +
	"\vsum_seconds\x18\x04 \x01(\x03R\n" +
	"sumSeconds2\xf3\x01\n" +
	"\x10AnalyticsService\x12^\n" +
	"\x0fGetGeneralStats\x12$.analytics.v1.GetGeneralStatsRequest\x1a%.analytics.v1.GetGeneralStatsResponse\x12\x7f\n" +
	"\x1aGetAverageLengthByCategory\x12/.analytics.v1.GetAverageLengthByCategoryRequest\x1a0.analytics.v1.GetAverageLengthByCategoryResponseBYZWgithub.com/CloudNativeDevelopmentTeamH/analytics/backend/proto/analytics/v1;analyticsv1b\x06proto3"

var (
	file_analytics_v1_analytics_proto_rawDescOnce sync.Once
	file_analytics_v1_analytics_proto_rawDescData []byte
)

func file_analytics_v1_analytics_proto_rawDescGZIP() []byte {
	file_analytics_v1_analytics_proto_rawDescOnce.Do(func() {
		file_analytics_v1_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_v1_analytics_proto_rawDesc), len(file_analytics_v1_analytics_proto_rawDesc)))
	})
	return file_analytics_v1_analytics_proto_rawDescData
}

var file_analytics_v1_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_analytics_v1_analytics_proto_goTypes = []any{
	(*GetGeneralStatsRequest)(nil),             // 0: analytics.v1.GetGeneralStatsRequest
	(*CategoryShare)(nil),                      // 1: analytics.v1.CategoryShare
	(*GetGeneralStatsResponse)(nil),            // 2: analytics.v1.GetGeneralStatsResponse
	(*GetAverageLengthByCategoryRequest)(nil),  // 3: analytics.v1.GetAverageLengthByCategoryRequest
	(*GetAverageLengthByCategoryResponse)(nil), // 4: analytics.v1.GetAverageLengthByCategoryResponse
}
var file_analytics_v1_analytics_proto_depIdxs = []int32{
	1, // 0: analytics.v1.GetGeneralStatsResponse.category_shares:type_name -> analytics.v1.CategoryShare
	0, // 1: analytics.v1.AnalyticsService.GetGeneralStats:input_type -> analytics.v1.GetGeneralStatsRequest
	3, // 2: analytics.v1.AnalyticsService.GetAverageLengthByCategory:input_type -> analytics.v1.GetAverageLengthByCategoryRequest
	2, // 3: analytics.v1.AnalyticsService.GetGeneralStats:output_type -> analytics.v1.GetGeneralStatsResponse
	4, // 4: analytics.v1.AnalyticsService.GetAverageLengthByCategory:output_type -> analytics.v1.GetAverageLengthByCategoryResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_analytics_v1_analytics_proto_init() }
func file_analytics_v1_analytics_proto_init() {
	if File_analytics_v1_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_v1_analytics_proto_rawDesc), len(file_analytics_v1_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_v1_analytics_proto_goTypes,
		DependencyIndexes: file_analytics_v1_analytics_proto_depIdxs,
		MessageInfos:      file_analytics_v1_analytics_proto_msgTypes,
	}.Build()
	File_analytics_v1_analytics_proto = out.File
	file_analytics_v1_analytics_proto_goTypes = nil
	file_analytics_v1_analytics_proto_depIdxs = nil
}
